[openai]
api_key = "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"

[email]
user = "gvanshika170@gmail.com"
password = "gauosywsoklyuspe"
